### ISSUE TITLE
gtf2gtf --help error

### ISSUE THREAD

**Issue by IanSudbery** [cgat-developers/cgat-apps#76]
After installing cgat-apps from conda in a fresh env, I get

```
Traceback (most recent call last):
  File "/shared/sudlab1/General/projects/test_project/env/bin/cgat", line 11, in <module>
    sys.exit(main())
  File "/shared/sudlab1/General/projects/test_project/env/lib/python3.7/site-packages/cgat/cgat.py", line 132, in main
    module.main(sys.argv)
  File "/shared/sudlab1/General/projects/test_project/env/lib/python3.7/site-packages/cgat/tools/gtf2gtf.py", line 540, in main
    (args) = E.start(parser, argv=argv)
  File "/shared/sudlab1/General/projects/test_project/env/lib/python3.7/site-packages/cgatcore/experiment.py", line 1213, in start
    global_args, unknown = parser.parse_known_args(argv[1:])
  File "/shared/sudlab1/General/projects/test_project/env/lib/python3.7/argparse.py", line 1787, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/shared/sudlab1/General/projects/test_project/env/lib/python3.7/argparse.py", line 1993, in _parse_known_args
    start_index = consume_optional(start_index)
  File "/shared/sudlab1/General/projects/test_project/env/lib/python3.7/argparse.py", line 1933, in consume_optional
    take_action(action, args, option_string)
  File "/shared/sudlab1/General/projects/test_project/env/lib/python3.7/argparse.py", line 1861, in take_action
    action(self, namespace, argument_values, option_string)
  File "/shared/sudlab1/General/projects/test_project/env/lib/python3.7/argparse.py", line 1043, in __call__
    parser.print_help()
  File "/shared/sudlab1/General/projects/test_project/env/lib/python3.7/argparse.py", line 2481, in print_help
    self._print_message(self.format_help(), file)
  File "/shared/sudlab1/General/projects/test_project/env/lib/python3.7/argparse.py", line 2465, in format_help
    return formatter.format_help()
  File "/shared/sudlab1/General/projects/test_project/env/lib/python3.7/argparse.py", line 284, in format_help
    help = self._root_section.format_help()
  File "/shared/sudlab1/General/projects/test_project/env/lib/python3.7/argparse.py", line 215, in format_help
    item_help = join([func(*args) for func, args in self.items])
  File "/shared/sudlab1/General/projects/test_project/env/lib/python3.7/argparse.py", line 215, in <listcomp>
    item_help = join([func(*args) for func, args in self.items])
  File "/shared/sudlab1/General/projects/test_project/env/lib/python3.7/argparse.py", line 215, in format_help
    item_help = join([func(*args) for func, args in self.items])
  File "/shared/sudlab1/General/projects/test_project/env/lib/python3.7/argparse.py", line 215, in <listcomp>
    item_help = join([func(*args) for func, args in self.items])
  File "/shared/sudlab1/General/projects/test_project/env/lib/python3.7/argparse.py", line 531, in _format_action
    help_text = self._expand_help(action)
  File "/shared/sudlab1/General/projects/test_project/env/lib/python3.7/argparse.py", line 620, in _expand_help
    return self._get_help_string(action) % params
TypeError: %i format: a number is required, not dict
```

**Comment by IanSudbery** [comment]
This is caused by two instances of `\\%i` in the help text for two options. 

https://github.com/cgat-developers/cgat-apps/blob/4ac9f37ea625dda0206075f9d3eced3113c30a17/cgat/tools/gtf2gtf.py#L372-L375

But I don't understand, if this is the case, why tests are passing.

**Comment by sebastian-luna-valero** [comment]
FYI: I restarted a Travis build on the master branch: 

https://travis-ci.org/github/cgat-developers/cgat-apps/builds/743004625

**Comment by Acribbs** [comment]
Hmm Biopython removed a module and the test fail. I have a ton of work to do at the moment, but I will get around to fixing this in the next few weeks.
